# Generated by Django 2.1.5 on 2019-01-29 23:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190129_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to=home.models.img_path),
        ),
    ]
