# Generated by Django 2.1.5 on 2019-01-30 06:00

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190130_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='fi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('describtion', models.TextField()),
                ('img', models.FileField(blank=True, upload_to=home.models.img_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('files', models.FileField(blank=True, upload_to=home.models.img_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
